const ACTION_TYPES = {
  GET_TASKS_ACTION: "GET_TASKS_ACTION",
  GET_TASKS_REQUEST: "GET_TASKS_REQUEST",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  GET_TASKS_ERROR: "GET_TASKS_ERROR",

  CREATE_TASK_ACTION: "CREATE_TASK_ACTION",
  CREATE_TASK_REQUEST: "CREATE_TASK_REQUEST",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_ERROR: "CREATE_TASK_ERROR",

  DELETE_TASK_ACTION: "DELETE_TASK_ACTION",
  DELETE_TASK_REQUEST: "DELETE_TASK_REQUEST",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_ERROR: "DELETE_TASK_ERROR",
};

export default ACTION_TYPES;
